import React, { useEffect, useMemo, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import * as pdfjsLib from 'pdfjs-dist';
import { Copy, Download, FileText, MoreHorizontal, Paperclip, Plus, Send, Settings, Sparkles, Trash2, X, Pencil, RefreshCw, Globe, UserRound, Check, ChevronDown, PanelLeft, LogOut } from 'lucide-react';
import { MODELS, DEFAULT_SETTINGS, uid } from './config.js';
import { askOpenRouter, extractText, getApiKey, loadSettings, saveSettings, setApiKey } from './openrouter.js';
import { auth, firebaseConfigured } from './firebase.js';
import { createUserWithEmailAndPassword, deleteUser, onAuthStateChanged, signInWithEmailAndPassword, signOut, updateProfile } from 'firebase/auth';

pdfjsLib.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.mjs', import.meta.url).toString();
const STORAGE = 'luma.chats';
const readChats = () => { try { return JSON.parse(localStorage.getItem(STORAGE) || '[]'); } catch { return []; } };
const writeChats = chats => localStorage.setItem(STORAGE, JSON.stringify(chats));

function Modal({ title, children, onClose, actions }) { return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><header><h2>{title}</h2><button className="icon-btn" onClick={onClose}><X size={18}/></button></header><div className="modal-body">{children}</div>{actions&&<footer>{actions}</footer>}</div></div>; }

function AttachmentCard({ item, removable, onRemove }) { return <button className="attachment-card" onClick={()=>item.dataUrl&&window.open(item.dataUrl,'_blank','noopener,noreferrer')}><span className="file-icon">{item.kind==='image'?<img src={item.dataUrl} alt=""/>:<FileText size={18}/>}</span><span className="file-meta"><b>{item.name}</b><small>{item.type||'file'}</small></span>{removable&&<span className="attachment-remove" onClick={e=>{e.preventDefault();e.stopPropagation();onRemove?.();}}><X size={14}/></span>}</button>; }

function CodeBlock({ inline, children, className }) {
  if(inline) return <code className="inline-code">{children}</code>;
  const code=String(children).replace(/\n$/,''); const lang=className?.replace('language-','')||''; const [preview,setPreview]=useState(false);
  const ext=({html:'html',svg:'svg',javascript:'js',js:'js',typescript:'ts',ts:'ts',css:'css',json:'json',python:'py'})[lang]||'txt';
  const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([code],{type:'text/plain'}));a.download=`luma-code.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  return <div className="code-wrap"><div className="code-tools"><span>{lang||'code'}</span><div><button onClick={()=>navigator.clipboard?.writeText(code)}><Copy size={13}/>コピー</button><button onClick={download}><Download size={13}/>保存</button>{(lang==='html'||lang==='svg')&&<button onClick={()=>setPreview(v=>!v)}>{preview?'コード':'プレビュー'}</button>}</div></div>{preview?<iframe className="code-preview" title="preview" sandbox="allow-scripts" srcDoc={lang==='svg'?`<body style="margin:0">${code}</body>`:code}/>:<pre><code>{code}</code></pre>}</div>;
}

function Message({ message, onEdit, onRegenerate }) { const copy=()=>navigator.clipboard?.writeText(message.content||''); return <article className={`message-row ${message.role}`}><div className="message-bubble">{message.attachments?.length>0&&<div className="message-attachments">{message.attachments.map(a=><AttachmentCard key={a.id} item={a}/>)}</div>}{message.role==='assistant'?<ReactMarkdown remarkPlugins={[remarkGfm]} components={{code:CodeBlock}}>{message.content}</ReactMarkdown>:<div className="plain-text">{message.content}</div>}</div><div className="message-actions"><button onClick={copy} title="コピー"><Copy size={14}/></button>{message.role==='user'?<button onClick={()=>onEdit(message)} title="編集"><Pencil size={14}/></button>:<button onClick={()=>onRegenerate(message)} title="この地点から再生成"><RefreshCw size={14}/></button>}</div></article>; }

function SettingsPanel({ settings,setSettings,close,user,setUser }) {
  const [tab,setTab]=useState('account'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [api,setApi]=useState(getApiKey()); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  const update=patch=>{const next={...settings,...patch};setSettings(next);saveSettings(next);};
  const authAction=async mode=>{setNotice('');setBusy(true);try{if(!auth)throw new Error('Firebaseが設定されていません。');if(mode==='login')await signInWithEmailAndPassword(auth,email,password);else{const c=await createUserWithEmailAndPassword(auth,email,password);if(settings.displayName)await updateProfile(c.user,{displayName:settings.displayName});}setNotice('完了しました。');}catch(e){setNotice(e.message);}finally{setBusy(false);}};
  const logout=async()=>{if(auth)await signOut(auth);setUser(null);};
  const removeAccount=async()=>{if(!auth?.currentUser)return;if(!window.confirm('アカウントを完全に削除しますか？この操作は取り消せません。'))return;setBusy(true);try{await deleteUser(auth.currentUser);setUser(null);setNotice('アカウントを削除しました。');}catch(e){setNotice(e.message);}finally{setBusy(false);}};
  const tabs=[['account','アカウント'],['api','API'],['personal','Personal Intelligence'],['design','デザイン']];
  return <div className="settings-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="settings-panel"><header className="settings-header"><div><span className="eyebrow">Luma</span><h2>設定</h2></div><button className="icon-btn" onClick={close}><X size={19}/></button></header><nav className="settings-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><main className="settings-content">
    {tab==='account'&&<section className="settings-section"><div className="section-intro"><h3>アカウント</h3><p>ログインすると、LumaのアカウントをFirebaseで管理できます。</p></div>{firebaseConfigured?user?<><div className="profile-card"><div className="large-avatar">{(user.displayName||settings.displayName||'L')[0].toUpperCase()}</div><div><strong>{user.displayName||'Luma User'}</strong><span>{user.email}</span></div></div><label>アカウント名<input value={settings.displayName} onChange={e=>update({displayName:e.target.value})}/></label><div className="button-row"><button className="secondary" onClick={logout}><LogOut size={15}/>ログアウト</button><button className="danger" onClick={removeAccount} disabled={busy}>アカウントを削除</button></div></>:<><label>メールアドレス<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>パスワード<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><div className="button-row"><button onClick={()=>authAction('login')} disabled={busy}>ログイン</button><button className="secondary" onClick={()=>authAction('signup')} disabled={busy}>アカウントを作成</button></div></>:<div className="info-box">Firebaseの環境変数を設定するとアカウント機能が有効になります。現在はローカルモードで利用できます。</div>}{notice&&<div className="notice">{notice}</div>}</section>}
    {tab==='api'&&<section className="settings-section"><div className="section-intro"><h3>API</h3><p>OpenRouterのキーはこのブラウザのローカルストレージに保存します。GitHubへ送信しません。</p></div><label>OpenRouter APIキー<input type="password" value={api} onChange={e=>setApi(e.target.value)} placeholder="sk-or-..." autoComplete="off"/></label><button onClick={()=>{setApiKey(api.trim());setNotice('APIキーを保存しました。')}}><Check size={15}/>保存</button>{notice&&<div className="notice">{notice}</div>}<div className="models-heading"><h4>利用モデル</h4><span>{MODELS.length} models</span></div><div className="model-list">{MODELS.map(m=><div className="model-item" key={m.id}><div><b>{m.name}</b><span>{m.hint}</span></div><code>{m.id}</code></div>)}</div></section>}
    {tab==='personal'&&<section className="settings-section"><div className="section-intro"><h3>Personal Intelligence</h3><p>Lumaがあなたへの応答を調整するための情報です。</p></div><label>AIにどう呼ばれたいですか？<input value={settings.displayName} onChange={e=>update({displayName:e.target.value})}/></label><label>カスタム指示<textarea rows="8" value={settings.customInstructions} onChange={e=>update({customInstructions:e.target.value})} placeholder="回答の好み、知っておいてほしいこと、避けてほしいことなど"/></label></section>}
    {tab==='design'&&<section className="settings-section"><div className="section-intro"><h3>デザイン</h3><p>Lumaの見た目と読みやすさを調整できます。</p></div><label>アクセントカラー<div className="color-field"><input type="color" value={settings.accent} onChange={e=>update({accent:e.target.value})}/><code>{settings.accent}</code></div></label><label>テーマ<select value={settings.theme} onChange={e=>update({theme:e.target.value})}><option value="system">システム</option><option value="light">ライト</option><option value="dark">ダーク</option></select></label><label>フォント<select value={settings.font} onChange={e=>update({font:e.target.value})}><option value="system">システム</option><option value="sans">Sans</option><option value="serif">Serif</option></select></label></section>}
  </main></aside></div>;
}

export default function App(){
  const [settings,setSettings]=useState(()=>loadSettings(DEFAULT_SETTINGS)); const [chats,setChats]=useState(readChats); const [activeId,setActiveId]=useState(null); const [sidebar,setSidebar]=useState(()=>window.innerWidth>=900); const [settingsOpen,setSettingsOpen]=useState(false); const [input,setInput]=useState(''); const [attachments,setAttachments]=useState([]); const [loading,setLoading]=useState(false); const [user,setUser]=useState(null); const [editing,setEditing]=useState(null); const [menuId,setMenuId]=useState(null); const [modal,setModal]=useState(null); const fileRef=useRef(); const textareaRef=useRef(); const endRef=useRef();
  const active=chats.find(c=>c.id===activeId)||null; const currentModel=MODELS.find(m=>m.id===settings.model)||MODELS[0]; const sorted=useMemo(()=>[...chats].sort((a,b)=>b.updatedAt-a.updatedAt),[chats]);
  useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.font=settings.font;document.documentElement.style.setProperty('--accent',settings.accent);},[settings]); useEffect(()=>{if(auth)return onAuthStateChanged(auth,setUser);},[]); useEffect(()=>writeChats(chats),[chats]); useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'});},[active?.messages?.length,loading]);
  useEffect(()=>{const close=e=>{if(!e.target.closest('.chat-menu'))setMenuId(null)};document.addEventListener('click',close);return()=>document.removeEventListener('click',close);},[]);
  const createChat=()=>{const c={id:uid('chat'),title:'新しいチャット',messages:[],createdAt:Date.now(),updatedAt:Date.now()};setChats(p=>[c,...p]);setActiveId(c.id);if(window.innerWidth<900)setSidebar(false);}; const updateChat=(id,patch)=>setChats(p=>p.map(c=>c.id===id?{...c,...patch,updatedAt:Date.now()}:c)); const chooseChat=id=>{setActiveId(id);setMenuId(null);if(window.innerWidth<900)setSidebar(false);};
  const rename=c=>{setMenuId(null);setModal({type:'rename',chat:c,value:c.title});}; const remove=c=>{setMenuId(null);setModal({type:'delete',chat:c});}; const confirmModal=()=>{if(!modal)return;if(modal.type==='rename'&&modal.value.trim())updateChat(modal.chat.id,{title:modal.value.trim()});if(modal.type==='delete'){setChats(p=>p.filter(x=>x.id!==modal.chat.id));if(activeId===modal.chat.id)setActiveId(null);}setModal(null);};
  const generateTitle=async text=>{const fallback=text.replace(/\s+/g,' ').slice(0,28)+(text.length>28?'…':'');if(!getApiKey())return fallback;try{const r=await askOpenRouter({messages:[{role:'user',content:`次の入力から日本語の短いチャットタイトルを1つだけ作ってください。15文字以内。タイトルだけ返してください。\n${text}`}],model:settings.model,settings:{...settings,webSearch:false}});return extractText(r).replace(/[「」\n]/g,'').trim().slice(0,24)||fallback;}catch{return fallback;}};
  const readFile=async file=>{const dataUrl=file.type.startsWith('image/')?await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);}):null;let extractedText='';if(file.type.startsWith('text/'))extractedText=await file.text();if(file.type==='application/pdf'){try{const buffer=await file.arrayBuffer();const pdf=await pdfjsLib.getDocument({data:buffer}).promise;const pages=[];for(let i=1;i<=Math.min(pdf.numPages,40);i++){const page=await pdf.getPage(i);const tc=await page.getTextContent();pages.push(tc.items.map(x=>x.str).join(' '));}extractedText=pages.join('\n\n');}catch{extractedText='PDFのテキストを読み取れませんでした。';}}return{id:uid('file'),name:file.name,type:file.type,kind:file.type.startsWith('image/')?'image':'file',dataUrl,extractedText};};
  const handleFiles=async list=>{const files=[...list].filter(f=>f.type.startsWith('image/')||f.type==='application/pdf'||f.type.startsWith('text/'));if(!files.length)return;const next=[];for(const f of files)next.push(await readFile(f));setAttachments(p=>[...p,...next]);};
  const send=async(customText=null,historyOverride=null,customAttachments=null)=>{const text=(customText??input).trim();const files=customAttachments??attachments;if(!text&&!files.length||loading)return;let c=active;if(!c){c={id:uid('chat'),title:'新しいチャット',messages:[],createdAt:Date.now(),updatedAt:Date.now()};setChats(p=>[c,...p]);setActiveId(c.id);}const userMsg={id:uid('msg'),role:'user',content:text,attachments:files};const history=historyOverride??[...c.messages,userMsg];updateChat(c.id,{messages:history});setInput('');setAttachments([]);setLoading(true);try{const r=await askOpenRouter({messages:history.map(m=>({role:m.role,content:m.content})),model:settings.model,settings,attachments:userMsg.attachments});const answer={id:uid('msg'),role:'assistant',content:extractText(r),model:settings.model,sources:r?.choices?.[0]?.message?.annotations||[]};const title=c.messages.length===0?await generateTitle(text||files[0]?.name||'添付ファイル'):c.title;updateChat(c.id,{messages:[...history,answer],title});}catch(e){updateChat(c.id,{messages:[...history,{id:uid('msg'),role:'assistant',content:`**エラー**\n\n${e.message}`} ]});}finally{setLoading(false);}};
  const regenerate=async msg=>{if(!active||loading)return;const idx=active.messages.findIndex(m=>m.id===msg.id);if(idx<0)return;const prior=active.messages.slice(0,idx);const lastUser=[...prior].reverse().find(m=>m.role==='user');if(!lastUser)return;setLoading(true);updateChat(active.id,{messages:prior});try{const r=await askOpenRouter({messages:prior.map(m=>({role:m.role,content:m.content})),model:msg.model||settings.model,settings,attachments:lastUser.attachments||[]});updateChat(active.id,{messages:[...prior,{id:uid('msg'),role:'assistant',content:extractText(r),model:msg.model||settings.model,sources:r?.choices?.[0]?.message?.annotations||[]}]});}catch(e){updateChat(active.id,{messages:[...prior,{id:uid('msg'),role:'assistant',content:`**エラー**\n\n${e.message}`} ]});}finally{setLoading(false);}};
  const editMessage=msg=>{setEditing(msg);setInput(msg.content);setTimeout(()=>textareaRef.current?.focus(),0);}; const submitEdit=async()=>{if(!editing||!active)return;const idx=active.messages.findIndex(m=>m.id===editing.id);const prior=active.messages.slice(0,idx);const files=editing.attachments||[];setEditing(null);await send(input,[...prior,{...editing,content:input}],files);}; const onSubmit=e=>{e.preventDefault();editing?submitEdit():send();}; const onKeyDown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();onSubmit(e);}};
  return <div className="app-shell" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();handleFiles(e.dataTransfer.files)}}>{sidebar&&<div className="sidebar-scrim" onClick={()=>setSidebar(false)}/>}<aside className={`sidebar ${sidebar?'is-open':''}`}><div className="sidebar-top"><button className="brand" onClick={()=>setActiveId(null)}><span className="logo">L</span><span>Luma</span></button><button className="icon-btn sidebar-close" onClick={()=>setSidebar(false)}><X size={18}/></button></div><button className="new-chat" onClick={createChat}><Plus size={17}/>新規チャット</button><div className="chat-list"><div className="list-label">チャット</div>{sorted.length?sorted.map(c=><div className={`chat-item ${c.id===activeId?'active':''}`} key={c.id} onClick={()=>chooseChat(c.id)}><span>{c.title}</span><div className="chat-menu"><button className="chat-more-btn" onClick={e=>{e.stopPropagation();setMenuId(menuId===c.id?null:c.id)}}><MoreHorizontal size={17}/></button>{menuId===c.id&&<div className="chat-menu-pop"><button onClick={()=>rename(c)}><Pencil size={14}/>名前を変更</button><button className="danger-text" onClick={()=>remove(c)}><Trash2 size={14}/>削除</button></div>}</div></div>):<div className="empty-chats">まだチャットはありません</div>}</div><button className="account-box" onClick={()=>setSettingsOpen(true)}><span className="avatar">{(user?.displayName||settings.displayName||'L')[0].toUpperCase()}</span><span className="account-copy"><b>{user?.displayName||settings.displayName||'Luma'}</b><small>設定</small></span><Settings size={16}/></button></aside>
  <main className="main"><header className="topbar"><div className="topbar-left"><button className="icon-btn" onClick={()=>setSidebar(v=>!v)} title="サイドバー"><PanelLeft size={18}/></button>{active&&<span className="mobile-title">{active.title}</span>}</div><button className="model-chip" onClick={()=>setModal({type:'model'})}><span className="model-dot"/>{currentModel.name}<ChevronDown size={14}/></button></header>
  {!active||!active.messages.length?<div className="welcome"><div className="welcome-mark"><Sparkles size={20}/></div><h1>{active?'何を一緒に考えますか？':'Luma'}</h1><p>{active?'モデルを選んで、質問やアイデアを入力してください。':'複数のAIモデルを、ひとつの場所から。'}</p>{!active&&<button onClick={createChat}>新しいチャットを始める</button>}</div>:<div className="chat-view"><div className="messages">{active.messages.map(m=><Message key={m.id} message={m} onEdit={editMessage} onRegenerate={regenerate}/>)}{loading&&<div className="typing-row"><div className="typing"><i/><i/><i/></div></div>}<div ref={endRef}/></div></div>}
  <div className="composer-area"><form className={`composer ${editing?'is-editing':''}`} onSubmit={onSubmit}>{editing&&<div className="editing-bar"><Pencil size={13}/>メッセージを編集中<button type="button" onClick={()=>{setEditing(null);setInput('')}}><X size={14}/></button></div>}{attachments.length>0&&<div className="attachment-strip">{attachments.map((a,i)=><AttachmentCard key={a.id} item={a} removable onRemove={()=>setAttachments(p=>p.filter((_,x)=>x!==i))}/>)}</div>}<textarea ref={textareaRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={onKeyDown} placeholder="Lumaにメッセージ…" rows={1}/><div className="composer-bottom"><button type="button" className="composer-icon" onClick={()=>fileRef.current?.click()} title="ファイルを添付"><Paperclip size={18}/></button><input ref={fileRef} hidden type="file" multiple accept="image/*,.pdf,.txt,.md,.csv,.json" onChange={e=>{handleFiles(e.target.files);e.target.value=''}}/><label className={`search-toggle ${settings.webSearch?'on':''}`}><Globe size={15}/><span>Web検索</span><input type="checkbox" checked={settings.webSearch} onChange={e=>{const next={...settings,webSearch:e.target.checked};setSettings(next);saveSettings(next)}}/></label><span className="composer-spacer"/><button type="button" className="model-select" onClick={()=>setModal({type:'model'})}>{currentModel.name}<ChevronDown size={13}/></button><button className="send-btn" disabled={loading||(!input.trim()&&!attachments.length)} title={editing?'更新':'送信'}>{editing?<Check size={17}/>:<Send size={16}/>}</button></div></form><div className="composer-note">Enterで送信 · Shift + Enterで改行 · LumaはAIモデルを選んで使えるワークスペースです</div></div></main>
  {settingsOpen&&<SettingsPanel settings={settings} setSettings={setSettings} close={()=>setSettingsOpen(false)} user={user} setUser={setUser}/>} {modal?.type==='rename'&&<Modal title="チャット名を変更" onClose={()=>setModal(null)} actions={<><button className="secondary" onClick={()=>setModal(null)}>キャンセル</button><button onClick={confirmModal}>保存</button></>}><label className="modal-label">チャット名<input autoFocus value={modal.value} onChange={e=>setModal({...modal,value:e.target.value})} onKeyDown={e=>e.key==='Enter'&&confirmModal()}/></label></Modal>}{modal?.type==='delete'&&<Modal title="チャットを削除" onClose={()=>setModal(null)} actions={<><button className="secondary" onClick={()=>setModal(null)}>キャンセル</button><button className="danger" onClick={confirmModal}>削除する</button></>}><p>「{modal.chat.title}」を削除します。この操作は取り消せません。</p></Modal>}{modal?.type==='model'&&<Modal title="モデルを選択" onClose={()=>setModal(null)}><div className="model-picker">{MODELS.map(m=><button key={m.id} className={settings.model===m.id?'selected':''} onClick={()=>{const next={...settings,model:m.id};setSettings(next);saveSettings(next);setModal(null)}}><span><b>{m.name}</b><small>{m.hint}</small></span>{settings.model===m.id&&<Check size={16}/>}</button>)}</div></Modal>}</div>;
}
